import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import RecoilRootWrapper from '../../wrappers/RecoilRootWrapper'
import Header from '../../components/layout/header'
import Footer from '../../components/layout/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const layoutStyle = {
    'background-color' : 'white',
} as React.CSSProperties;

const bodyStyle = {
    'background-color' : '#cccccc', // use bg-color while testing
    'display' : 'flex',
    'flex-direction' : 'column',
    'justify-content' : 'start',
    // 'align-items' : 'center',
    // 'padding' : '2vh 4rem 2vh 4rem',
    'min-height' : '50vh',
    'font-family' : 'HakgyoansimGaeulsopungB',
} as React.CSSProperties;

/*
    font-family: 'NanumSquareRoundLight';
    font-family: 'NanumSquareRound';
    font-family: 'NanumSquareRoundBold';
    font-family: 'NanumSquareRoundExtraBold';
*/

export default function RootLayout({ children, }: { children: React.ReactNode }) {
    return (
        <html lang="ko">
            <head>
                <title>hihangeol</title>
            </head>

            <body 
                className={inter.className}
                style={layoutStyle}
            >    
                <Header />
                <div style={bodyStyle} >
                    <RecoilRootWrapper>
                        {children}
                    </RecoilRootWrapper>
                </div>
                <Footer />
            </body>
        </html>
    )
}
